// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContentAPIProto.proto

package com.ak.pubsub.poc.proto.domain;

public final class ContentAPIProto {
  private ContentAPIProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContentAPIOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ContentAPI)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ContentAPI.SubType subType = 1;</code>
     */
    boolean hasSubType();
    /**
     * <code>required .ContentAPI.SubType subType = 1;</code>
     */
    ContentAPIProto.ContentAPI.SubType getSubType();

    /**
     * <code>repeated .Instrument instruments = 2;</code>
     */
    java.util.List<CommonProto.Instrument>
        getInstrumentsList();
    /**
     * <code>repeated .Instrument instruments = 2;</code>
     */
    CommonProto.Instrument getInstruments(int index);
    /**
     * <code>repeated .Instrument instruments = 2;</code>
     */
    int getInstrumentsCount();
    /**
     * <code>repeated .Instrument instruments = 2;</code>
     */
    java.util.List<? extends CommonProto.InstrumentOrBuilder>
        getInstrumentsOrBuilderList();
    /**
     * <code>repeated .Instrument instruments = 2;</code>
     */
    CommonProto.InstrumentOrBuilder getInstrumentsOrBuilder(
        int index);

    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    java.util.List<CommonProto.LinkedParameter>
        getLinkedParamatersList();
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    CommonProto.LinkedParameter getLinkedParamaters(int index);
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    int getLinkedParamatersCount();
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    java.util.List<? extends CommonProto.LinkedParameterOrBuilder>
        getLinkedParamatersOrBuilderList();
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    CommonProto.LinkedParameterOrBuilder getLinkedParamatersOrBuilder(
        int index);

    /**
     * <code>optional string identifier = 4;</code>
     */
    boolean hasIdentifier();
    /**
     * <code>optional string identifier = 4;</code>
     */
    java.lang.String getIdentifier();
    /**
     * <code>optional string identifier = 4;</code>
     */
    com.google.protobuf.ByteString
        getIdentifierBytes();

    /**
     * <code>optional int32 identifierType = 5;</code>
     */
    boolean hasIdentifierType();
    /**
     * <code>optional int32 identifierType = 5;</code>
     */
    int getIdentifierType();

    /**
     * <code>optional int64 startTime = 6;</code>
     */
    boolean hasStartTime();
    /**
     * <code>optional int64 startTime = 6;</code>
     */
    long getStartTime();

    /**
     * <code>optional int64 endTime = 7;</code>
     */
    boolean hasEndTime();
    /**
     * <code>optional int64 endTime = 7;</code>
     */
    long getEndTime();

    /**
     * <code>optional int64 startSid = 8;</code>
     */
    boolean hasStartSid();
    /**
     * <code>optional int64 startSid = 8;</code>
     */
    long getStartSid();

    /**
     * <code>optional int64 endSid = 9;</code>
     */
    boolean hasEndSid();
    /**
     * <code>optional int64 endSid = 9;</code>
     */
    long getEndSid();

    /**
     * <code>optional int32 frequency = 10;</code>
     */
    boolean hasFrequency();
    /**
     * <code>optional int32 frequency = 10;</code>
     */
    int getFrequency();

    /**
     * <code>optional string JSON = 11;</code>
     */
    boolean hasJSON();
    /**
     * <code>optional string JSON = 11;</code>
     */
    java.lang.String getJSON();
    /**
     * <code>optional string JSON = 11;</code>
     */
    com.google.protobuf.ByteString
        getJSONBytes();

    /**
     * <code>optional int32 sourceId = 12;</code>
     */
    boolean hasSourceId();
    /**
     * <code>optional int32 sourceId = 12;</code>
     */
    int getSourceId();

    /**
     * <code>optional .Status status = 13;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .Status status = 13;</code>
     */
    CommonProto.Status getStatus();
    /**
     * <code>optional .Status status = 13;</code>
     */
    CommonProto.StatusOrBuilder getStatusOrBuilder();
  }
  /**
   * Protobuf type {@code ContentAPI}
   */
  public  static final class ContentAPI extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ContentAPI)
      ContentAPIOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContentAPI.newBuilder() to construct.
    private ContentAPI(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContentAPI() {
      subType_ = 1;
      instruments_ = java.util.Collections.emptyList();
      linkedParamaters_ = java.util.Collections.emptyList();
      identifier_ = "";
      identifierType_ = 0;
      startTime_ = 0L;
      endTime_ = 0L;
      startSid_ = 0L;
      endSid_ = 0L;
      frequency_ = 0;
      jSON_ = "";
      sourceId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContentAPI(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ContentAPIProto.ContentAPI.SubType value = ContentAPIProto.ContentAPI.SubType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                subType_ = rawValue;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                instruments_ = new java.util.ArrayList<CommonProto.Instrument>();
                mutable_bitField0_ |= 0x00000002;
              }
              instruments_.add(
                  input.readMessage(CommonProto.Instrument.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                linkedParamaters_ = new java.util.ArrayList<CommonProto.LinkedParameter>();
                mutable_bitField0_ |= 0x00000004;
              }
              linkedParamaters_.add(
                  input.readMessage(CommonProto.LinkedParameter.PARSER, extensionRegistry));
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              identifier_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              identifierType_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              startTime_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              endTime_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000020;
              startSid_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000040;
              endSid_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000080;
              frequency_ = input.readInt32();
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              jSON_ = bs;
              break;
            }
            case 96: {
              bitField0_ |= 0x00000200;
              sourceId_ = input.readInt32();
              break;
            }
            case 106: {
              CommonProto.Status.Builder subBuilder = null;
              if (((bitField0_ & 0x00000400) == 0x00000400)) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(CommonProto.Status.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000400;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          instruments_ = java.util.Collections.unmodifiableList(instruments_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          linkedParamaters_ = java.util.Collections.unmodifiableList(linkedParamaters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ContentAPIProto.internal_static_ContentAPI_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ContentAPIProto.internal_static_ContentAPI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ContentAPIProto.ContentAPI.class, ContentAPIProto.ContentAPI.Builder.class);
    }

    /**
     * Protobuf enum {@code ContentAPI.SubType}
     */
    public enum SubType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CLOSE_SESSION = 1;</code>
       */
      CLOSE_SESSION(1),
      /**
       * <code>SUBSCRIBE_L1 = 2;</code>
       */
      SUBSCRIBE_L1(2),
      /**
       * <code>SUBSCRIBE_L2 = 3;</code>
       */
      SUBSCRIBE_L2(3),
      /**
       * <code>SNAPSHOT_L1 = 4;</code>
       */
      SNAPSHOT_L1(4),
      /**
       * <code>SNAPSHOT_L2 = 5;</code>
       */
      SNAPSHOT_L2(5),
      /**
       * <code>UNSUBSCRIBE_L1 = 6;</code>
       */
      UNSUBSCRIBE_L1(6),
      /**
       * <code>UNSUBSCRIBE_L2 = 7;</code>
       */
      UNSUBSCRIBE_L2(7),
      /**
       * <code>GET_INSTRUMENT = 8;</code>
       */
      GET_INSTRUMENT(8),
      /**
       * <code>ROLLUP_HIST = 9;</code>
       */
      ROLLUP_HIST(9),
      /**
       * <code>ROLLUP_SUBSCRIBE_L1 = 10;</code>
       */
      ROLLUP_SUBSCRIBE_L1(10),
      /**
       * <code>ROLLUP_SUBSCRIBE_L2 = 11;</code>
       */
      ROLLUP_SUBSCRIBE_L2(11),
      /**
       * <code>ROLLUP_UNSUBSCRIBE_L1 = 12;</code>
       */
      ROLLUP_UNSUBSCRIBE_L1(12),
      /**
       * <code>ROLLUP_UNSUBSCRIBE_L2 = 13;</code>
       */
      ROLLUP_UNSUBSCRIBE_L2(13),
      /**
       * <code>VALUE_ADD_SUBSCRIBE_L1 = 14;</code>
       */
      VALUE_ADD_SUBSCRIBE_L1(14),
      /**
       * <code>VALUE_ADD_UNSUBSCRIBE_L1 = 15;</code>
       */
      VALUE_ADD_UNSUBSCRIBE_L1(15),
      /**
       * <code>VALUE_ADD_SNAPSHOT_L1 = 16;</code>
       */
      VALUE_ADD_SNAPSHOT_L1(16),
      /**
       * <code>UTILITIES_SUB_UNSUB = 17;</code>
       */
      UTILITIES_SUB_UNSUB(17),
      /**
       * <code>GAINERS_LOSERS_SUBSCRIBE_IN = 18;</code>
       */
      GAINERS_LOSERS_SUBSCRIBE_IN(18),
      /**
       * <code>GAINERS_LOSERS_UNSUBSCRIBE_IN = 19;</code>
       */
      GAINERS_LOSERS_UNSUBSCRIBE_IN(19),
      /**
       * <code>GAINERS_LOSERS_SNAPSHOT_IN = 20;</code>
       */
      GAINERS_LOSERS_SNAPSHOT_IN(20),
      /**
       * <code>GAINERS_LOSERS_SUBSCRIBE_EX = 21;</code>
       */
      GAINERS_LOSERS_SUBSCRIBE_EX(21),
      /**
       * <code>GAINERS_LOSERS_UNSUBSCRIBE_EX = 22;</code>
       */
      GAINERS_LOSERS_UNSUBSCRIBE_EX(22),
      /**
       * <code>GAINERS_LOSERS_SNAPSHOT_EX = 23;</code>
       */
      GAINERS_LOSERS_SNAPSHOT_EX(23),
      ;

      /**
       * <code>CLOSE_SESSION = 1;</code>
       */
      public static final int CLOSE_SESSION_VALUE = 1;
      /**
       * <code>SUBSCRIBE_L1 = 2;</code>
       */
      public static final int SUBSCRIBE_L1_VALUE = 2;
      /**
       * <code>SUBSCRIBE_L2 = 3;</code>
       */
      public static final int SUBSCRIBE_L2_VALUE = 3;
      /**
       * <code>SNAPSHOT_L1 = 4;</code>
       */
      public static final int SNAPSHOT_L1_VALUE = 4;
      /**
       * <code>SNAPSHOT_L2 = 5;</code>
       */
      public static final int SNAPSHOT_L2_VALUE = 5;
      /**
       * <code>UNSUBSCRIBE_L1 = 6;</code>
       */
      public static final int UNSUBSCRIBE_L1_VALUE = 6;
      /**
       * <code>UNSUBSCRIBE_L2 = 7;</code>
       */
      public static final int UNSUBSCRIBE_L2_VALUE = 7;
      /**
       * <code>GET_INSTRUMENT = 8;</code>
       */
      public static final int GET_INSTRUMENT_VALUE = 8;
      /**
       * <code>ROLLUP_HIST = 9;</code>
       */
      public static final int ROLLUP_HIST_VALUE = 9;
      /**
       * <code>ROLLUP_SUBSCRIBE_L1 = 10;</code>
       */
      public static final int ROLLUP_SUBSCRIBE_L1_VALUE = 10;
      /**
       * <code>ROLLUP_SUBSCRIBE_L2 = 11;</code>
       */
      public static final int ROLLUP_SUBSCRIBE_L2_VALUE = 11;
      /**
       * <code>ROLLUP_UNSUBSCRIBE_L1 = 12;</code>
       */
      public static final int ROLLUP_UNSUBSCRIBE_L1_VALUE = 12;
      /**
       * <code>ROLLUP_UNSUBSCRIBE_L2 = 13;</code>
       */
      public static final int ROLLUP_UNSUBSCRIBE_L2_VALUE = 13;
      /**
       * <code>VALUE_ADD_SUBSCRIBE_L1 = 14;</code>
       */
      public static final int VALUE_ADD_SUBSCRIBE_L1_VALUE = 14;
      /**
       * <code>VALUE_ADD_UNSUBSCRIBE_L1 = 15;</code>
       */
      public static final int VALUE_ADD_UNSUBSCRIBE_L1_VALUE = 15;
      /**
       * <code>VALUE_ADD_SNAPSHOT_L1 = 16;</code>
       */
      public static final int VALUE_ADD_SNAPSHOT_L1_VALUE = 16;
      /**
       * <code>UTILITIES_SUB_UNSUB = 17;</code>
       */
      public static final int UTILITIES_SUB_UNSUB_VALUE = 17;
      /**
       * <code>GAINERS_LOSERS_SUBSCRIBE_IN = 18;</code>
       */
      public static final int GAINERS_LOSERS_SUBSCRIBE_IN_VALUE = 18;
      /**
       * <code>GAINERS_LOSERS_UNSUBSCRIBE_IN = 19;</code>
       */
      public static final int GAINERS_LOSERS_UNSUBSCRIBE_IN_VALUE = 19;
      /**
       * <code>GAINERS_LOSERS_SNAPSHOT_IN = 20;</code>
       */
      public static final int GAINERS_LOSERS_SNAPSHOT_IN_VALUE = 20;
      /**
       * <code>GAINERS_LOSERS_SUBSCRIBE_EX = 21;</code>
       */
      public static final int GAINERS_LOSERS_SUBSCRIBE_EX_VALUE = 21;
      /**
       * <code>GAINERS_LOSERS_UNSUBSCRIBE_EX = 22;</code>
       */
      public static final int GAINERS_LOSERS_UNSUBSCRIBE_EX_VALUE = 22;
      /**
       * <code>GAINERS_LOSERS_SNAPSHOT_EX = 23;</code>
       */
      public static final int GAINERS_LOSERS_SNAPSHOT_EX_VALUE = 23;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SubType valueOf(int value) {
        return forNumber(value);
      }

      public static SubType forNumber(int value) {
        switch (value) {
          case 1: return CLOSE_SESSION;
          case 2: return SUBSCRIBE_L1;
          case 3: return SUBSCRIBE_L2;
          case 4: return SNAPSHOT_L1;
          case 5: return SNAPSHOT_L2;
          case 6: return UNSUBSCRIBE_L1;
          case 7: return UNSUBSCRIBE_L2;
          case 8: return GET_INSTRUMENT;
          case 9: return ROLLUP_HIST;
          case 10: return ROLLUP_SUBSCRIBE_L1;
          case 11: return ROLLUP_SUBSCRIBE_L2;
          case 12: return ROLLUP_UNSUBSCRIBE_L1;
          case 13: return ROLLUP_UNSUBSCRIBE_L2;
          case 14: return VALUE_ADD_SUBSCRIBE_L1;
          case 15: return VALUE_ADD_UNSUBSCRIBE_L1;
          case 16: return VALUE_ADD_SNAPSHOT_L1;
          case 17: return UTILITIES_SUB_UNSUB;
          case 18: return GAINERS_LOSERS_SUBSCRIBE_IN;
          case 19: return GAINERS_LOSERS_UNSUBSCRIBE_IN;
          case 20: return GAINERS_LOSERS_SNAPSHOT_IN;
          case 21: return GAINERS_LOSERS_SUBSCRIBE_EX;
          case 22: return GAINERS_LOSERS_UNSUBSCRIBE_EX;
          case 23: return GAINERS_LOSERS_SNAPSHOT_EX;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SubType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SubType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SubType>() {
              public SubType findValueByNumber(int number) {
                return SubType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ContentAPIProto.ContentAPI.getDescriptor().getEnumTypes().get(0);
      }

      private static final SubType[] VALUES = values();

      public static SubType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SubType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ContentAPI.SubType)
    }

    private int bitField0_;
    public static final int SUBTYPE_FIELD_NUMBER = 1;
    private int subType_;
    /**
     * <code>required .ContentAPI.SubType subType = 1;</code>
     */
    public boolean hasSubType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ContentAPI.SubType subType = 1;</code>
     */
    public ContentAPIProto.ContentAPI.SubType getSubType() {
      ContentAPIProto.ContentAPI.SubType result = ContentAPIProto.ContentAPI.SubType.valueOf(subType_);
      return result == null ? ContentAPIProto.ContentAPI.SubType.CLOSE_SESSION : result;
    }

    public static final int INSTRUMENTS_FIELD_NUMBER = 2;
    private java.util.List<CommonProto.Instrument> instruments_;
    /**
     * <code>repeated .Instrument instruments = 2;</code>
     */
    public java.util.List<CommonProto.Instrument> getInstrumentsList() {
      return instruments_;
    }
    /**
     * <code>repeated .Instrument instruments = 2;</code>
     */
    public java.util.List<? extends CommonProto.InstrumentOrBuilder>
        getInstrumentsOrBuilderList() {
      return instruments_;
    }
    /**
     * <code>repeated .Instrument instruments = 2;</code>
     */
    public int getInstrumentsCount() {
      return instruments_.size();
    }
    /**
     * <code>repeated .Instrument instruments = 2;</code>
     */
    public CommonProto.Instrument getInstruments(int index) {
      return instruments_.get(index);
    }
    /**
     * <code>repeated .Instrument instruments = 2;</code>
     */
    public CommonProto.InstrumentOrBuilder getInstrumentsOrBuilder(
        int index) {
      return instruments_.get(index);
    }

    public static final int LINKEDPARAMATERS_FIELD_NUMBER = 3;
    private java.util.List<CommonProto.LinkedParameter> linkedParamaters_;
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    public java.util.List<CommonProto.LinkedParameter> getLinkedParamatersList() {
      return linkedParamaters_;
    }
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    public java.util.List<? extends CommonProto.LinkedParameterOrBuilder>
        getLinkedParamatersOrBuilderList() {
      return linkedParamaters_;
    }
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    public int getLinkedParamatersCount() {
      return linkedParamaters_.size();
    }
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    public CommonProto.LinkedParameter getLinkedParamaters(int index) {
      return linkedParamaters_.get(index);
    }
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    public CommonProto.LinkedParameterOrBuilder getLinkedParamatersOrBuilder(
        int index) {
      return linkedParamaters_.get(index);
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 4;
    private volatile java.lang.Object identifier_;
    /**
     * <code>optional string identifier = 4;</code>
     */
    public boolean hasIdentifier() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string identifier = 4;</code>
     */
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          identifier_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string identifier = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTIFIERTYPE_FIELD_NUMBER = 5;
    private int identifierType_;
    /**
     * <code>optional int32 identifierType = 5;</code>
     */
    public boolean hasIdentifierType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 identifierType = 5;</code>
     */
    public int getIdentifierType() {
      return identifierType_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 6;
    private long startTime_;
    /**
     * <code>optional int64 startTime = 6;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 startTime = 6;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 7;
    private long endTime_;
    /**
     * <code>optional int64 endTime = 7;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 endTime = 7;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    public static final int STARTSID_FIELD_NUMBER = 8;
    private long startSid_;
    /**
     * <code>optional int64 startSid = 8;</code>
     */
    public boolean hasStartSid() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 startSid = 8;</code>
     */
    public long getStartSid() {
      return startSid_;
    }

    public static final int ENDSID_FIELD_NUMBER = 9;
    private long endSid_;
    /**
     * <code>optional int64 endSid = 9;</code>
     */
    public boolean hasEndSid() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 endSid = 9;</code>
     */
    public long getEndSid() {
      return endSid_;
    }

    public static final int FREQUENCY_FIELD_NUMBER = 10;
    private int frequency_;
    /**
     * <code>optional int32 frequency = 10;</code>
     */
    public boolean hasFrequency() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 frequency = 10;</code>
     */
    public int getFrequency() {
      return frequency_;
    }

    public static final int JSON_FIELD_NUMBER = 11;
    private volatile java.lang.Object jSON_;
    /**
     * <code>optional string JSON = 11;</code>
     */
    public boolean hasJSON() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string JSON = 11;</code>
     */
    public java.lang.String getJSON() {
      java.lang.Object ref = jSON_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jSON_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string JSON = 11;</code>
     */
    public com.google.protobuf.ByteString
        getJSONBytes() {
      java.lang.Object ref = jSON_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jSON_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCEID_FIELD_NUMBER = 12;
    private int sourceId_;
    /**
     * <code>optional int32 sourceId = 12;</code>
     */
    public boolean hasSourceId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 sourceId = 12;</code>
     */
    public int getSourceId() {
      return sourceId_;
    }

    public static final int STATUS_FIELD_NUMBER = 13;
    private CommonProto.Status status_;
    /**
     * <code>optional .Status status = 13;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional .Status status = 13;</code>
     */
    public CommonProto.Status getStatus() {
      return status_ == null ? CommonProto.Status.getDefaultInstance() : status_;
    }
    /**
     * <code>optional .Status status = 13;</code>
     */
    public CommonProto.StatusOrBuilder getStatusOrBuilder() {
      return status_ == null ? CommonProto.Status.getDefaultInstance() : status_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSubType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, subType_);
      }
      for (int i = 0; i < instruments_.size(); i++) {
        output.writeMessage(2, instruments_.get(i));
      }
      for (int i = 0; i < linkedParamaters_.size(); i++) {
        output.writeMessage(3, linkedParamaters_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, identifier_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(5, identifierType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(6, startTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(7, endTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(8, startSid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(9, endSid_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(10, frequency_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, jSON_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(12, sourceId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeMessage(13, getStatus());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, subType_);
      }
      for (int i = 0; i < instruments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, instruments_.get(i));
      }
      for (int i = 0; i < linkedParamaters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, linkedParamaters_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, identifier_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, identifierType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, startTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, endTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, startSid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, endSid_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, frequency_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, jSON_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, sourceId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getStatus());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ContentAPIProto.ContentAPI)) {
        return super.equals(obj);
      }
      ContentAPIProto.ContentAPI other = (ContentAPIProto.ContentAPI) obj;

      boolean result = true;
      result = result && (hasSubType() == other.hasSubType());
      if (hasSubType()) {
        result = result && subType_ == other.subType_;
      }
      result = result && getInstrumentsList()
          .equals(other.getInstrumentsList());
      result = result && getLinkedParamatersList()
          .equals(other.getLinkedParamatersList());
      result = result && (hasIdentifier() == other.hasIdentifier());
      if (hasIdentifier()) {
        result = result && getIdentifier()
            .equals(other.getIdentifier());
      }
      result = result && (hasIdentifierType() == other.hasIdentifierType());
      if (hasIdentifierType()) {
        result = result && (getIdentifierType()
            == other.getIdentifierType());
      }
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && (getStartTime()
            == other.getStartTime());
      }
      result = result && (hasEndTime() == other.hasEndTime());
      if (hasEndTime()) {
        result = result && (getEndTime()
            == other.getEndTime());
      }
      result = result && (hasStartSid() == other.hasStartSid());
      if (hasStartSid()) {
        result = result && (getStartSid()
            == other.getStartSid());
      }
      result = result && (hasEndSid() == other.hasEndSid());
      if (hasEndSid()) {
        result = result && (getEndSid()
            == other.getEndSid());
      }
      result = result && (hasFrequency() == other.hasFrequency());
      if (hasFrequency()) {
        result = result && (getFrequency()
            == other.getFrequency());
      }
      result = result && (hasJSON() == other.hasJSON());
      if (hasJSON()) {
        result = result && getJSON()
            .equals(other.getJSON());
      }
      result = result && (hasSourceId() == other.hasSourceId());
      if (hasSourceId()) {
        result = result && (getSourceId()
            == other.getSourceId());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && getStatus()
            .equals(other.getStatus());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSubType()) {
        hash = (37 * hash) + SUBTYPE_FIELD_NUMBER;
        hash = (53 * hash) + subType_;
      }
      if (getInstrumentsCount() > 0) {
        hash = (37 * hash) + INSTRUMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getInstrumentsList().hashCode();
      }
      if (getLinkedParamatersCount() > 0) {
        hash = (37 * hash) + LINKEDPARAMATERS_FIELD_NUMBER;
        hash = (53 * hash) + getLinkedParamatersList().hashCode();
      }
      if (hasIdentifier()) {
        hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getIdentifier().hashCode();
      }
      if (hasIdentifierType()) {
        hash = (37 * hash) + IDENTIFIERTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getIdentifierType();
      }
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTime());
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEndTime());
      }
      if (hasStartSid()) {
        hash = (37 * hash) + STARTSID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartSid());
      }
      if (hasEndSid()) {
        hash = (37 * hash) + ENDSID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEndSid());
      }
      if (hasFrequency()) {
        hash = (37 * hash) + FREQUENCY_FIELD_NUMBER;
        hash = (53 * hash) + getFrequency();
      }
      if (hasJSON()) {
        hash = (37 * hash) + JSON_FIELD_NUMBER;
        hash = (53 * hash) + getJSON().hashCode();
      }
      if (hasSourceId()) {
        hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
        hash = (53 * hash) + getSourceId();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ContentAPIProto.ContentAPI parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ContentAPIProto.ContentAPI parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ContentAPIProto.ContentAPI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ContentAPIProto.ContentAPI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ContentAPIProto.ContentAPI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ContentAPIProto.ContentAPI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ContentAPIProto.ContentAPI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ContentAPIProto.ContentAPI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ContentAPIProto.ContentAPI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ContentAPIProto.ContentAPI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ContentAPIProto.ContentAPI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ContentAPIProto.ContentAPI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ContentAPIProto.ContentAPI prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ContentAPI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ContentAPI)
        ContentAPIProto.ContentAPIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ContentAPIProto.internal_static_ContentAPI_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ContentAPIProto.internal_static_ContentAPI_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ContentAPIProto.ContentAPI.class, ContentAPIProto.ContentAPI.Builder.class);
      }

      // Construct using com.spcapitaliq.realtime.common.proto.domain.ContentAPIProto.ContentAPI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInstrumentsFieldBuilder();
          getLinkedParamatersFieldBuilder();
          getStatusFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        subType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (instrumentsBuilder_ == null) {
          instruments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          instrumentsBuilder_.clear();
        }
        if (linkedParamatersBuilder_ == null) {
          linkedParamaters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          linkedParamatersBuilder_.clear();
        }
        identifier_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        identifierType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        startSid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        endSid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        frequency_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        jSON_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        sourceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        if (statusBuilder_ == null) {
          status_ = null;
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ContentAPIProto.internal_static_ContentAPI_descriptor;
      }

      public ContentAPIProto.ContentAPI getDefaultInstanceForType() {
        return ContentAPIProto.ContentAPI.getDefaultInstance();
      }

      public ContentAPIProto.ContentAPI build() {
        ContentAPIProto.ContentAPI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ContentAPIProto.ContentAPI buildPartial() {
        ContentAPIProto.ContentAPI result = new ContentAPIProto.ContentAPI(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.subType_ = subType_;
        if (instrumentsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            instruments_ = java.util.Collections.unmodifiableList(instruments_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.instruments_ = instruments_;
        } else {
          result.instruments_ = instrumentsBuilder_.build();
        }
        if (linkedParamatersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            linkedParamaters_ = java.util.Collections.unmodifiableList(linkedParamaters_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.linkedParamaters_ = linkedParamaters_;
        } else {
          result.linkedParamaters_ = linkedParamatersBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.identifier_ = identifier_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.identifierType_ = identifierType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000020;
        }
        result.startSid_ = startSid_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000040;
        }
        result.endSid_ = endSid_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000080;
        }
        result.frequency_ = frequency_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000100;
        }
        result.jSON_ = jSON_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000200;
        }
        result.sourceId_ = sourceId_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000400;
        }
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ContentAPIProto.ContentAPI) {
          return mergeFrom((ContentAPIProto.ContentAPI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ContentAPIProto.ContentAPI other) {
        if (other == ContentAPIProto.ContentAPI.getDefaultInstance()) return this;
        if (other.hasSubType()) {
          setSubType(other.getSubType());
        }
        if (instrumentsBuilder_ == null) {
          if (!other.instruments_.isEmpty()) {
            if (instruments_.isEmpty()) {
              instruments_ = other.instruments_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInstrumentsIsMutable();
              instruments_.addAll(other.instruments_);
            }
            onChanged();
          }
        } else {
          if (!other.instruments_.isEmpty()) {
            if (instrumentsBuilder_.isEmpty()) {
              instrumentsBuilder_.dispose();
              instrumentsBuilder_ = null;
              instruments_ = other.instruments_;
              bitField0_ = (bitField0_ & ~0x00000002);
              instrumentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInstrumentsFieldBuilder() : null;
            } else {
              instrumentsBuilder_.addAllMessages(other.instruments_);
            }
          }
        }
        if (linkedParamatersBuilder_ == null) {
          if (!other.linkedParamaters_.isEmpty()) {
            if (linkedParamaters_.isEmpty()) {
              linkedParamaters_ = other.linkedParamaters_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureLinkedParamatersIsMutable();
              linkedParamaters_.addAll(other.linkedParamaters_);
            }
            onChanged();
          }
        } else {
          if (!other.linkedParamaters_.isEmpty()) {
            if (linkedParamatersBuilder_.isEmpty()) {
              linkedParamatersBuilder_.dispose();
              linkedParamatersBuilder_ = null;
              linkedParamaters_ = other.linkedParamaters_;
              bitField0_ = (bitField0_ & ~0x00000004);
              linkedParamatersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLinkedParamatersFieldBuilder() : null;
            } else {
              linkedParamatersBuilder_.addAllMessages(other.linkedParamaters_);
            }
          }
        }
        if (other.hasIdentifier()) {
          bitField0_ |= 0x00000008;
          identifier_ = other.identifier_;
          onChanged();
        }
        if (other.hasIdentifierType()) {
          setIdentifierType(other.getIdentifierType());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasStartSid()) {
          setStartSid(other.getStartSid());
        }
        if (other.hasEndSid()) {
          setEndSid(other.getEndSid());
        }
        if (other.hasFrequency()) {
          setFrequency(other.getFrequency());
        }
        if (other.hasJSON()) {
          bitField0_ |= 0x00000400;
          jSON_ = other.jSON_;
          onChanged();
        }
        if (other.hasSourceId()) {
          setSourceId(other.getSourceId());
        }
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSubType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ContentAPIProto.ContentAPI parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ContentAPIProto.ContentAPI) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int subType_ = 1;
      /**
       * <code>required .ContentAPI.SubType subType = 1;</code>
       */
      public boolean hasSubType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ContentAPI.SubType subType = 1;</code>
       */
      public ContentAPIProto.ContentAPI.SubType getSubType() {
        ContentAPIProto.ContentAPI.SubType result = ContentAPIProto.ContentAPI.SubType.valueOf(subType_);
        return result == null ? ContentAPIProto.ContentAPI.SubType.CLOSE_SESSION : result;
      }
      /**
       * <code>required .ContentAPI.SubType subType = 1;</code>
       */
      public Builder setSubType(ContentAPIProto.ContentAPI.SubType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        subType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .ContentAPI.SubType subType = 1;</code>
       */
      public Builder clearSubType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        subType_ = 1;
        onChanged();
        return this;
      }

      private java.util.List<CommonProto.Instrument> instruments_ =
        java.util.Collections.emptyList();
      private void ensureInstrumentsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          instruments_ = new java.util.ArrayList<CommonProto.Instrument>(instruments_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CommonProto.Instrument, CommonProto.Instrument.Builder, CommonProto.InstrumentOrBuilder> instrumentsBuilder_;

      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public java.util.List<CommonProto.Instrument> getInstrumentsList() {
        if (instrumentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(instruments_);
        } else {
          return instrumentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public int getInstrumentsCount() {
        if (instrumentsBuilder_ == null) {
          return instruments_.size();
        } else {
          return instrumentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public CommonProto.Instrument getInstruments(int index) {
        if (instrumentsBuilder_ == null) {
          return instruments_.get(index);
        } else {
          return instrumentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public Builder setInstruments(
          int index, CommonProto.Instrument value) {
        if (instrumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentsIsMutable();
          instruments_.set(index, value);
          onChanged();
        } else {
          instrumentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public Builder setInstruments(
          int index, CommonProto.Instrument.Builder builderForValue) {
        if (instrumentsBuilder_ == null) {
          ensureInstrumentsIsMutable();
          instruments_.set(index, builderForValue.build());
          onChanged();
        } else {
          instrumentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public Builder addInstruments(CommonProto.Instrument value) {
        if (instrumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentsIsMutable();
          instruments_.add(value);
          onChanged();
        } else {
          instrumentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public Builder addInstruments(
          int index, CommonProto.Instrument value) {
        if (instrumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentsIsMutable();
          instruments_.add(index, value);
          onChanged();
        } else {
          instrumentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public Builder addInstruments(
          CommonProto.Instrument.Builder builderForValue) {
        if (instrumentsBuilder_ == null) {
          ensureInstrumentsIsMutable();
          instruments_.add(builderForValue.build());
          onChanged();
        } else {
          instrumentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public Builder addInstruments(
          int index, CommonProto.Instrument.Builder builderForValue) {
        if (instrumentsBuilder_ == null) {
          ensureInstrumentsIsMutable();
          instruments_.add(index, builderForValue.build());
          onChanged();
        } else {
          instrumentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public Builder addAllInstruments(
          java.lang.Iterable<? extends CommonProto.Instrument> values) {
        if (instrumentsBuilder_ == null) {
          ensureInstrumentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, instruments_);
          onChanged();
        } else {
          instrumentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public Builder clearInstruments() {
        if (instrumentsBuilder_ == null) {
          instruments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          instrumentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public Builder removeInstruments(int index) {
        if (instrumentsBuilder_ == null) {
          ensureInstrumentsIsMutable();
          instruments_.remove(index);
          onChanged();
        } else {
          instrumentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public CommonProto.Instrument.Builder getInstrumentsBuilder(
          int index) {
        return getInstrumentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public CommonProto.InstrumentOrBuilder getInstrumentsOrBuilder(
          int index) {
        if (instrumentsBuilder_ == null) {
          return instruments_.get(index);  } else {
          return instrumentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public java.util.List<? extends CommonProto.InstrumentOrBuilder>
           getInstrumentsOrBuilderList() {
        if (instrumentsBuilder_ != null) {
          return instrumentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(instruments_);
        }
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public CommonProto.Instrument.Builder addInstrumentsBuilder() {
        return getInstrumentsFieldBuilder().addBuilder(
            CommonProto.Instrument.getDefaultInstance());
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public CommonProto.Instrument.Builder addInstrumentsBuilder(
          int index) {
        return getInstrumentsFieldBuilder().addBuilder(
            index, CommonProto.Instrument.getDefaultInstance());
      }
      /**
       * <code>repeated .Instrument instruments = 2;</code>
       */
      public java.util.List<CommonProto.Instrument.Builder>
           getInstrumentsBuilderList() {
        return getInstrumentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CommonProto.Instrument, CommonProto.Instrument.Builder, CommonProto.InstrumentOrBuilder>
          getInstrumentsFieldBuilder() {
        if (instrumentsBuilder_ == null) {
          instrumentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CommonProto.Instrument, CommonProto.Instrument.Builder, CommonProto.InstrumentOrBuilder>(
                  instruments_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          instruments_ = null;
        }
        return instrumentsBuilder_;
      }

      private java.util.List<CommonProto.LinkedParameter> linkedParamaters_ =
        java.util.Collections.emptyList();
      private void ensureLinkedParamatersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          linkedParamaters_ = new java.util.ArrayList<CommonProto.LinkedParameter>(linkedParamaters_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CommonProto.LinkedParameter, CommonProto.LinkedParameter.Builder, CommonProto.LinkedParameterOrBuilder> linkedParamatersBuilder_;

      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public java.util.List<CommonProto.LinkedParameter> getLinkedParamatersList() {
        if (linkedParamatersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(linkedParamaters_);
        } else {
          return linkedParamatersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public int getLinkedParamatersCount() {
        if (linkedParamatersBuilder_ == null) {
          return linkedParamaters_.size();
        } else {
          return linkedParamatersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public CommonProto.LinkedParameter getLinkedParamaters(int index) {
        if (linkedParamatersBuilder_ == null) {
          return linkedParamaters_.get(index);
        } else {
          return linkedParamatersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder setLinkedParamaters(
          int index, CommonProto.LinkedParameter value) {
        if (linkedParamatersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.set(index, value);
          onChanged();
        } else {
          linkedParamatersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder setLinkedParamaters(
          int index, CommonProto.LinkedParameter.Builder builderForValue) {
        if (linkedParamatersBuilder_ == null) {
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.set(index, builderForValue.build());
          onChanged();
        } else {
          linkedParamatersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder addLinkedParamaters(CommonProto.LinkedParameter value) {
        if (linkedParamatersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.add(value);
          onChanged();
        } else {
          linkedParamatersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder addLinkedParamaters(
          int index, CommonProto.LinkedParameter value) {
        if (linkedParamatersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.add(index, value);
          onChanged();
        } else {
          linkedParamatersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder addLinkedParamaters(
          CommonProto.LinkedParameter.Builder builderForValue) {
        if (linkedParamatersBuilder_ == null) {
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.add(builderForValue.build());
          onChanged();
        } else {
          linkedParamatersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder addLinkedParamaters(
          int index, CommonProto.LinkedParameter.Builder builderForValue) {
        if (linkedParamatersBuilder_ == null) {
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.add(index, builderForValue.build());
          onChanged();
        } else {
          linkedParamatersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder addAllLinkedParamaters(
          java.lang.Iterable<? extends CommonProto.LinkedParameter> values) {
        if (linkedParamatersBuilder_ == null) {
          ensureLinkedParamatersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, linkedParamaters_);
          onChanged();
        } else {
          linkedParamatersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder clearLinkedParamaters() {
        if (linkedParamatersBuilder_ == null) {
          linkedParamaters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          linkedParamatersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder removeLinkedParamaters(int index) {
        if (linkedParamatersBuilder_ == null) {
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.remove(index);
          onChanged();
        } else {
          linkedParamatersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public CommonProto.LinkedParameter.Builder getLinkedParamatersBuilder(
          int index) {
        return getLinkedParamatersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public CommonProto.LinkedParameterOrBuilder getLinkedParamatersOrBuilder(
          int index) {
        if (linkedParamatersBuilder_ == null) {
          return linkedParamaters_.get(index);  } else {
          return linkedParamatersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public java.util.List<? extends CommonProto.LinkedParameterOrBuilder>
           getLinkedParamatersOrBuilderList() {
        if (linkedParamatersBuilder_ != null) {
          return linkedParamatersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(linkedParamaters_);
        }
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public CommonProto.LinkedParameter.Builder addLinkedParamatersBuilder() {
        return getLinkedParamatersFieldBuilder().addBuilder(
            CommonProto.LinkedParameter.getDefaultInstance());
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public CommonProto.LinkedParameter.Builder addLinkedParamatersBuilder(
          int index) {
        return getLinkedParamatersFieldBuilder().addBuilder(
            index, CommonProto.LinkedParameter.getDefaultInstance());
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public java.util.List<CommonProto.LinkedParameter.Builder>
           getLinkedParamatersBuilderList() {
        return getLinkedParamatersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CommonProto.LinkedParameter, CommonProto.LinkedParameter.Builder, CommonProto.LinkedParameterOrBuilder>
          getLinkedParamatersFieldBuilder() {
        if (linkedParamatersBuilder_ == null) {
          linkedParamatersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CommonProto.LinkedParameter, CommonProto.LinkedParameter.Builder, CommonProto.LinkedParameterOrBuilder>(
                  linkedParamaters_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          linkedParamaters_ = null;
        }
        return linkedParamatersBuilder_;
      }

      private java.lang.Object identifier_ = "";
      /**
       * <code>optional string identifier = 4;</code>
       */
      public boolean hasIdentifier() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string identifier = 4;</code>
       */
      public java.lang.String getIdentifier() {
        java.lang.Object ref = identifier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            identifier_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string identifier = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIdentifierBytes() {
        java.lang.Object ref = identifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string identifier = 4;</code>
       */
      public Builder setIdentifier(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        identifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string identifier = 4;</code>
       */
      public Builder clearIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000008);
        identifier_ = getDefaultInstance().getIdentifier();
        onChanged();
        return this;
      }
      /**
       * <code>optional string identifier = 4;</code>
       */
      public Builder setIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        identifier_ = value;
        onChanged();
        return this;
      }

      private int identifierType_ ;
      /**
       * <code>optional int32 identifierType = 5;</code>
       */
      public boolean hasIdentifierType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 identifierType = 5;</code>
       */
      public int getIdentifierType() {
        return identifierType_;
      }
      /**
       * <code>optional int32 identifierType = 5;</code>
       */
      public Builder setIdentifierType(int value) {
        bitField0_ |= 0x00000010;
        identifierType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 identifierType = 5;</code>
       */
      public Builder clearIdentifierType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        identifierType_ = 0;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>optional int64 startTime = 6;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 startTime = 6;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>optional int64 startTime = 6;</code>
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000020;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 startTime = 6;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>optional int64 endTime = 7;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 endTime = 7;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>optional int64 endTime = 7;</code>
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000040;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 endTime = 7;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private long startSid_ ;
      /**
       * <code>optional int64 startSid = 8;</code>
       */
      public boolean hasStartSid() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 startSid = 8;</code>
       */
      public long getStartSid() {
        return startSid_;
      }
      /**
       * <code>optional int64 startSid = 8;</code>
       */
      public Builder setStartSid(long value) {
        bitField0_ |= 0x00000080;
        startSid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 startSid = 8;</code>
       */
      public Builder clearStartSid() {
        bitField0_ = (bitField0_ & ~0x00000080);
        startSid_ = 0L;
        onChanged();
        return this;
      }

      private long endSid_ ;
      /**
       * <code>optional int64 endSid = 9;</code>
       */
      public boolean hasEndSid() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 endSid = 9;</code>
       */
      public long getEndSid() {
        return endSid_;
      }
      /**
       * <code>optional int64 endSid = 9;</code>
       */
      public Builder setEndSid(long value) {
        bitField0_ |= 0x00000100;
        endSid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 endSid = 9;</code>
       */
      public Builder clearEndSid() {
        bitField0_ = (bitField0_ & ~0x00000100);
        endSid_ = 0L;
        onChanged();
        return this;
      }

      private int frequency_ ;
      /**
       * <code>optional int32 frequency = 10;</code>
       */
      public boolean hasFrequency() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 frequency = 10;</code>
       */
      public int getFrequency() {
        return frequency_;
      }
      /**
       * <code>optional int32 frequency = 10;</code>
       */
      public Builder setFrequency(int value) {
        bitField0_ |= 0x00000200;
        frequency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 frequency = 10;</code>
       */
      public Builder clearFrequency() {
        bitField0_ = (bitField0_ & ~0x00000200);
        frequency_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object jSON_ = "";
      /**
       * <code>optional string JSON = 11;</code>
       */
      public boolean hasJSON() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string JSON = 11;</code>
       */
      public java.lang.String getJSON() {
        java.lang.Object ref = jSON_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jSON_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string JSON = 11;</code>
       */
      public com.google.protobuf.ByteString
          getJSONBytes() {
        java.lang.Object ref = jSON_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jSON_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string JSON = 11;</code>
       */
      public Builder setJSON(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        jSON_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string JSON = 11;</code>
       */
      public Builder clearJSON() {
        bitField0_ = (bitField0_ & ~0x00000400);
        jSON_ = getDefaultInstance().getJSON();
        onChanged();
        return this;
      }
      /**
       * <code>optional string JSON = 11;</code>
       */
      public Builder setJSONBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        jSON_ = value;
        onChanged();
        return this;
      }

      private int sourceId_ ;
      /**
       * <code>optional int32 sourceId = 12;</code>
       */
      public boolean hasSourceId() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 sourceId = 12;</code>
       */
      public int getSourceId() {
        return sourceId_;
      }
      /**
       * <code>optional int32 sourceId = 12;</code>
       */
      public Builder setSourceId(int value) {
        bitField0_ |= 0x00000800;
        sourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sourceId = 12;</code>
       */
      public Builder clearSourceId() {
        bitField0_ = (bitField0_ & ~0x00000800);
        sourceId_ = 0;
        onChanged();
        return this;
      }

      private CommonProto.Status status_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonProto.Status, CommonProto.Status.Builder, CommonProto.StatusOrBuilder> statusBuilder_;
      /**
       * <code>optional .Status status = 13;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional .Status status = 13;</code>
       */
      public CommonProto.Status getStatus() {
        if (statusBuilder_ == null) {
          return status_ == null ? CommonProto.Status.getDefaultInstance() : status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Status status = 13;</code>
       */
      public Builder setStatus(CommonProto.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      /**
       * <code>optional .Status status = 13;</code>
       */
      public Builder setStatus(
          CommonProto.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      /**
       * <code>optional .Status status = 13;</code>
       */
      public Builder mergeStatus(CommonProto.Status value) {
        if (statusBuilder_ == null) {
          if (((bitField0_ & 0x00001000) == 0x00001000) &&
              status_ != null &&
              status_ != CommonProto.Status.getDefaultInstance()) {
            status_ =
              CommonProto.Status.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      /**
       * <code>optional .Status status = 13;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = null;
          onChanged();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }
      /**
       * <code>optional .Status status = 13;</code>
       */
      public CommonProto.Status.Builder getStatusBuilder() {
        bitField0_ |= 0x00001000;
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Status status = 13;</code>
       */
      public CommonProto.StatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_ == null ?
              CommonProto.Status.getDefaultInstance() : status_;
        }
      }
      /**
       * <code>optional .Status status = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonProto.Status, CommonProto.Status.Builder, CommonProto.StatusOrBuilder>
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CommonProto.Status, CommonProto.Status.Builder, CommonProto.StatusOrBuilder>(
                  getStatus(),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ContentAPI)
    }

    // @@protoc_insertion_point(class_scope:ContentAPI)
    private static final ContentAPIProto.ContentAPI DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ContentAPIProto.ContentAPI();
    }

    public static ContentAPIProto.ContentAPI getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ContentAPI>
        PARSER = new com.google.protobuf.AbstractParser<ContentAPI>() {
      public ContentAPI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContentAPI(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContentAPI> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContentAPI> getParserForType() {
      return PARSER;
    }

    public ContentAPIProto.ContentAPI getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ContentAPI_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ContentAPI_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ContentAPIProto.proto\032\021CommonProto.pro" +
      "to\"\216\007\n\nContentAPI\022$\n\007subType\030\001 \002(\0162\023.Con" +
      "tentAPI.SubType\022 \n\013instruments\030\002 \003(\0132\013.I" +
      "nstrument\022*\n\020linkedParamaters\030\003 \003(\0132\020.Li" +
      "nkedParameter\022\022\n\nidentifier\030\004 \001(\t\022\026\n\016ide" +
      "ntifierType\030\005 \001(\005\022\021\n\tstartTime\030\006 \001(\003\022\017\n\007" +
      "endTime\030\007 \001(\003\022\020\n\010startSid\030\010 \001(\003\022\016\n\006endSi" +
      "d\030\t \001(\003\022\021\n\tfrequency\030\n \001(\005\022\014\n\004JSON\030\013 \001(\t" +
      "\022\020\n\010sourceId\030\014 \001(\005\022\027\n\006status\030\r \001(\0132\007.Sta" +
      "tus\"\315\004\n\007SubType\022\021\n\rCLOSE_SESSION\020\001\022\020\n\014SU" +
      "BSCRIBE_L1\020\002\022\020\n\014SUBSCRIBE_L2\020\003\022\017\n\013SNAPSH" +
      "OT_L1\020\004\022\017\n\013SNAPSHOT_L2\020\005\022\022\n\016UNSUBSCRIBE_" +
      "L1\020\006\022\022\n\016UNSUBSCRIBE_L2\020\007\022\022\n\016GET_INSTRUME" +
      "NT\020\010\022\017\n\013ROLLUP_HIST\020\t\022\027\n\023ROLLUP_SUBSCRIB" +
      "E_L1\020\n\022\027\n\023ROLLUP_SUBSCRIBE_L2\020\013\022\031\n\025ROLLU" +
      "P_UNSUBSCRIBE_L1\020\014\022\031\n\025ROLLUP_UNSUBSCRIBE" +
      "_L2\020\r\022\032\n\026VALUE_ADD_SUBSCRIBE_L1\020\016\022\034\n\030VAL" +
      "UE_ADD_UNSUBSCRIBE_L1\020\017\022\031\n\025VALUE_ADD_SNA" +
      "PSHOT_L1\020\020\022\027\n\023UTILITIES_SUB_UNSUB\020\021\022\037\n\033G" +
      "AINERS_LOSERS_SUBSCRIBE_IN\020\022\022!\n\035GAINERS_" +
      "LOSERS_UNSUBSCRIBE_IN\020\023\022\036\n\032GAINERS_LOSER" +
      "S_SNAPSHOT_IN\020\024\022\037\n\033GAINERS_LOSERS_SUBSCR" +
      "IBE_EX\020\025\022!\n\035GAINERS_LOSERS_UNSUBSCRIBE_E" +
      "X\020\026\022\036\n\032GAINERS_LOSERS_SNAPSHOT_EX\020\027B.\n,c" +
      "om.spcapitaliq.realtime.common.proto.dom" +
      "ain"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CommonProto.getDescriptor(),
        }, assigner);
    internal_static_ContentAPI_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ContentAPI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ContentAPI_descriptor,
        new java.lang.String[] { "SubType", "Instruments", "LinkedParamaters", "Identifier", "IdentifierType", "StartTime", "EndTime", "StartSid", "EndSid", "Frequency", "JSON", "SourceId", "Status", });
    CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
