// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataFieldsProto.proto

package com.ak.pubsub.poc.proto.domain;

public final class DataFieldsProto {
  private DataFieldsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataFieldsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataFields)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .DataFields.SubType subType = 1;</code>
     */
    boolean hasSubType();
    /**
     * <code>required .DataFields.SubType subType = 1;</code>
     */
    DataFieldsProto.DataFields.SubType getSubType();

    /**
     * <code>repeated .Instrument instrument = 2;</code>
     */
    java.util.List<CommonProto.Instrument>
        getInstrumentList();
    /**
     * <code>repeated .Instrument instrument = 2;</code>
     */
    CommonProto.Instrument getInstrument(int index);
    /**
     * <code>repeated .Instrument instrument = 2;</code>
     */
    int getInstrumentCount();
    /**
     * <code>repeated .Instrument instrument = 2;</code>
     */
    java.util.List<? extends CommonProto.InstrumentOrBuilder>
        getInstrumentOrBuilderList();
    /**
     * <code>repeated .Instrument instrument = 2;</code>
     */
    CommonProto.InstrumentOrBuilder getInstrumentOrBuilder(
        int index);

    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    java.util.List<CommonProto.LinkedParameter>
        getLinkedParamatersList();
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    CommonProto.LinkedParameter getLinkedParamaters(int index);
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    int getLinkedParamatersCount();
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    java.util.List<? extends CommonProto.LinkedParameterOrBuilder>
        getLinkedParamatersOrBuilderList();
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    CommonProto.LinkedParameterOrBuilder getLinkedParamatersOrBuilder(
        int index);

    /**
     * <code>optional int64 startTime = 5;</code>
     */
    boolean hasStartTime();
    /**
     * <code>optional int64 startTime = 5;</code>
     */
    long getStartTime();

    /**
     * <code>optional int64 endTime = 6;</code>
     */
    boolean hasEndTime();
    /**
     * <code>optional int64 endTime = 6;</code>
     */
    long getEndTime();

    /**
     * <code>optional .EndOfFrame endOfFrame = 7;</code>
     */
    boolean hasEndOfFrame();
    /**
     * <code>optional .EndOfFrame endOfFrame = 7;</code>
     */
    CommonProto.EndOfFrame getEndOfFrame();
    /**
     * <code>optional .EndOfFrame endOfFrame = 7;</code>
     */
    CommonProto.EndOfFrameOrBuilder getEndOfFrameOrBuilder();
  }
  /**
   * Protobuf type {@code DataFields}
   */
  public  static final class DataFields extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataFields)
      DataFieldsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataFields.newBuilder() to construct.
    private DataFields(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataFields() {
      subType_ = 1;
      instrument_ = java.util.Collections.emptyList();
      linkedParamaters_ = java.util.Collections.emptyList();
      startTime_ = 0L;
      endTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataFields(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              DataFieldsProto.DataFields.SubType value = DataFieldsProto.DataFields.SubType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                subType_ = rawValue;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                instrument_ = new java.util.ArrayList<CommonProto.Instrument>();
                mutable_bitField0_ |= 0x00000002;
              }
              instrument_.add(
                  input.readMessage(CommonProto.Instrument.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                linkedParamaters_ = new java.util.ArrayList<CommonProto.LinkedParameter>();
                mutable_bitField0_ |= 0x00000004;
              }
              linkedParamaters_.add(
                  input.readMessage(CommonProto.LinkedParameter.PARSER, extensionRegistry));
              break;
            }
            case 40: {
              bitField0_ |= 0x00000002;
              startTime_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000004;
              endTime_ = input.readInt64();
              break;
            }
            case 58: {
              CommonProto.EndOfFrame.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = endOfFrame_.toBuilder();
              }
              endOfFrame_ = input.readMessage(CommonProto.EndOfFrame.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(endOfFrame_);
                endOfFrame_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          instrument_ = java.util.Collections.unmodifiableList(instrument_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          linkedParamaters_ = java.util.Collections.unmodifiableList(linkedParamaters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataFieldsProto.internal_static_DataFields_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataFieldsProto.internal_static_DataFields_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataFieldsProto.DataFields.class, DataFieldsProto.DataFields.Builder.class);
    }

    /**
     * Protobuf enum {@code DataFields.SubType}
     */
    public enum SubType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEFAULT = 1;</code>
       */
      DEFAULT(1),
      /**
       * <code>UPDATE = 2;</code>
       */
      UPDATE(2),
      /**
       * <code>UNSUBSCRIBE = 3;</code>
       */
      UNSUBSCRIBE(3),
      /**
       * <code>SNAPSHOT = 4;</code>
       */
      SNAPSHOT(4),
      /**
       * <code>DEFAULT_GROUPING = 5;</code>
       */
      DEFAULT_GROUPING(5),
      /**
       * <code>UPDATE_GROUPING = 6;</code>
       */
      UPDATE_GROUPING(6),
      /**
       * <code>GET_HISTORY = 7;</code>
       */
      GET_HISTORY(7),
      /**
       * <code>UNSUBSCRIBE_GROUPING = 8;</code>
       */
      UNSUBSCRIBE_GROUPING(8),
      /**
       * <code>REF_UPDATE = 9;</code>
       */
      REF_UPDATE(9),
      ;

      /**
       * <code>DEFAULT = 1;</code>
       */
      public static final int DEFAULT_VALUE = 1;
      /**
       * <code>UPDATE = 2;</code>
       */
      public static final int UPDATE_VALUE = 2;
      /**
       * <code>UNSUBSCRIBE = 3;</code>
       */
      public static final int UNSUBSCRIBE_VALUE = 3;
      /**
       * <code>SNAPSHOT = 4;</code>
       */
      public static final int SNAPSHOT_VALUE = 4;
      /**
       * <code>DEFAULT_GROUPING = 5;</code>
       */
      public static final int DEFAULT_GROUPING_VALUE = 5;
      /**
       * <code>UPDATE_GROUPING = 6;</code>
       */
      public static final int UPDATE_GROUPING_VALUE = 6;
      /**
       * <code>GET_HISTORY = 7;</code>
       */
      public static final int GET_HISTORY_VALUE = 7;
      /**
       * <code>UNSUBSCRIBE_GROUPING = 8;</code>
       */
      public static final int UNSUBSCRIBE_GROUPING_VALUE = 8;
      /**
       * <code>REF_UPDATE = 9;</code>
       */
      public static final int REF_UPDATE_VALUE = 9;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SubType valueOf(int value) {
        return forNumber(value);
      }

      public static SubType forNumber(int value) {
        switch (value) {
          case 1: return DEFAULT;
          case 2: return UPDATE;
          case 3: return UNSUBSCRIBE;
          case 4: return SNAPSHOT;
          case 5: return DEFAULT_GROUPING;
          case 6: return UPDATE_GROUPING;
          case 7: return GET_HISTORY;
          case 8: return UNSUBSCRIBE_GROUPING;
          case 9: return REF_UPDATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SubType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SubType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SubType>() {
              public SubType findValueByNumber(int number) {
                return SubType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return DataFieldsProto.DataFields.getDescriptor().getEnumTypes().get(0);
      }

      private static final SubType[] VALUES = values();

      public static SubType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SubType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataFields.SubType)
    }

    private int bitField0_;
    public static final int SUBTYPE_FIELD_NUMBER = 1;
    private int subType_;
    /**
     * <code>required .DataFields.SubType subType = 1;</code>
     */
    public boolean hasSubType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .DataFields.SubType subType = 1;</code>
     */
    public DataFieldsProto.DataFields.SubType getSubType() {
      DataFieldsProto.DataFields.SubType result = DataFieldsProto.DataFields.SubType.valueOf(subType_);
      return result == null ? DataFieldsProto.DataFields.SubType.DEFAULT : result;
    }

    public static final int INSTRUMENT_FIELD_NUMBER = 2;
    private java.util.List<CommonProto.Instrument> instrument_;
    /**
     * <code>repeated .Instrument instrument = 2;</code>
     */
    public java.util.List<CommonProto.Instrument> getInstrumentList() {
      return instrument_;
    }
    /**
     * <code>repeated .Instrument instrument = 2;</code>
     */
    public java.util.List<? extends CommonProto.InstrumentOrBuilder>
        getInstrumentOrBuilderList() {
      return instrument_;
    }
    /**
     * <code>repeated .Instrument instrument = 2;</code>
     */
    public int getInstrumentCount() {
      return instrument_.size();
    }
    /**
     * <code>repeated .Instrument instrument = 2;</code>
     */
    public CommonProto.Instrument getInstrument(int index) {
      return instrument_.get(index);
    }
    /**
     * <code>repeated .Instrument instrument = 2;</code>
     */
    public CommonProto.InstrumentOrBuilder getInstrumentOrBuilder(
        int index) {
      return instrument_.get(index);
    }

    public static final int LINKEDPARAMATERS_FIELD_NUMBER = 3;
    private java.util.List<CommonProto.LinkedParameter> linkedParamaters_;
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    public java.util.List<CommonProto.LinkedParameter> getLinkedParamatersList() {
      return linkedParamaters_;
    }
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    public java.util.List<? extends CommonProto.LinkedParameterOrBuilder>
        getLinkedParamatersOrBuilderList() {
      return linkedParamaters_;
    }
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    public int getLinkedParamatersCount() {
      return linkedParamaters_.size();
    }
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    public CommonProto.LinkedParameter getLinkedParamaters(int index) {
      return linkedParamaters_.get(index);
    }
    /**
     * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
     */
    public CommonProto.LinkedParameterOrBuilder getLinkedParamatersOrBuilder(
        int index) {
      return linkedParamaters_.get(index);
    }

    public static final int STARTTIME_FIELD_NUMBER = 5;
    private long startTime_;
    /**
     * <code>optional int64 startTime = 5;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 startTime = 5;</code>
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 6;
    private long endTime_;
    /**
     * <code>optional int64 endTime = 6;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 endTime = 6;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    public static final int ENDOFFRAME_FIELD_NUMBER = 7;
    private CommonProto.EndOfFrame endOfFrame_;
    /**
     * <code>optional .EndOfFrame endOfFrame = 7;</code>
     */
    public boolean hasEndOfFrame() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .EndOfFrame endOfFrame = 7;</code>
     */
    public CommonProto.EndOfFrame getEndOfFrame() {
      return endOfFrame_ == null ? CommonProto.EndOfFrame.getDefaultInstance() : endOfFrame_;
    }
    /**
     * <code>optional .EndOfFrame endOfFrame = 7;</code>
     */
    public CommonProto.EndOfFrameOrBuilder getEndOfFrameOrBuilder() {
      return endOfFrame_ == null ? CommonProto.EndOfFrame.getDefaultInstance() : endOfFrame_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSubType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, subType_);
      }
      for (int i = 0; i < instrument_.size(); i++) {
        output.writeMessage(2, instrument_.get(i));
      }
      for (int i = 0; i < linkedParamaters_.size(); i++) {
        output.writeMessage(3, linkedParamaters_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(5, startTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(6, endTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(7, getEndOfFrame());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, subType_);
      }
      for (int i = 0; i < instrument_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, instrument_.get(i));
      }
      for (int i = 0; i < linkedParamaters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, linkedParamaters_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, startTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, endTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getEndOfFrame());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataFieldsProto.DataFields)) {
        return super.equals(obj);
      }
      DataFieldsProto.DataFields other = (DataFieldsProto.DataFields) obj;

      boolean result = true;
      result = result && (hasSubType() == other.hasSubType());
      if (hasSubType()) {
        result = result && subType_ == other.subType_;
      }
      result = result && getInstrumentList()
          .equals(other.getInstrumentList());
      result = result && getLinkedParamatersList()
          .equals(other.getLinkedParamatersList());
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && (getStartTime()
            == other.getStartTime());
      }
      result = result && (hasEndTime() == other.hasEndTime());
      if (hasEndTime()) {
        result = result && (getEndTime()
            == other.getEndTime());
      }
      result = result && (hasEndOfFrame() == other.hasEndOfFrame());
      if (hasEndOfFrame()) {
        result = result && getEndOfFrame()
            .equals(other.getEndOfFrame());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSubType()) {
        hash = (37 * hash) + SUBTYPE_FIELD_NUMBER;
        hash = (53 * hash) + subType_;
      }
      if (getInstrumentCount() > 0) {
        hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
        hash = (53 * hash) + getInstrumentList().hashCode();
      }
      if (getLinkedParamatersCount() > 0) {
        hash = (37 * hash) + LINKEDPARAMATERS_FIELD_NUMBER;
        hash = (53 * hash) + getLinkedParamatersList().hashCode();
      }
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTime());
      }
      if (hasEndTime()) {
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEndTime());
      }
      if (hasEndOfFrame()) {
        hash = (37 * hash) + ENDOFFRAME_FIELD_NUMBER;
        hash = (53 * hash) + getEndOfFrame().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataFieldsProto.DataFields parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataFieldsProto.DataFields parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataFieldsProto.DataFields parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataFieldsProto.DataFields parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataFieldsProto.DataFields parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataFieldsProto.DataFields parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataFieldsProto.DataFields parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataFieldsProto.DataFields parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataFieldsProto.DataFields parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DataFieldsProto.DataFields parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataFieldsProto.DataFields parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataFieldsProto.DataFields parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataFieldsProto.DataFields prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataFields}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataFields)
        DataFieldsProto.DataFieldsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataFieldsProto.internal_static_DataFields_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataFieldsProto.internal_static_DataFields_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataFieldsProto.DataFields.class, DataFieldsProto.DataFields.Builder.class);
      }

      // Construct using com.spcapitaliq.realtime.common.proto.domain.DataFieldsProto.DataFields.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInstrumentFieldBuilder();
          getLinkedParamatersFieldBuilder();
          getEndOfFrameFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        subType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (instrumentBuilder_ == null) {
          instrument_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          instrumentBuilder_.clear();
        }
        if (linkedParamatersBuilder_ == null) {
          linkedParamaters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          linkedParamatersBuilder_.clear();
        }
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (endOfFrameBuilder_ == null) {
          endOfFrame_ = null;
        } else {
          endOfFrameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataFieldsProto.internal_static_DataFields_descriptor;
      }

      public DataFieldsProto.DataFields getDefaultInstanceForType() {
        return DataFieldsProto.DataFields.getDefaultInstance();
      }

      public DataFieldsProto.DataFields build() {
        DataFieldsProto.DataFields result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DataFieldsProto.DataFields buildPartial() {
        DataFieldsProto.DataFields result = new DataFieldsProto.DataFields(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.subType_ = subType_;
        if (instrumentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            instrument_ = java.util.Collections.unmodifiableList(instrument_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.instrument_ = instrument_;
        } else {
          result.instrument_ = instrumentBuilder_.build();
        }
        if (linkedParamatersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            linkedParamaters_ = java.util.Collections.unmodifiableList(linkedParamaters_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.linkedParamaters_ = linkedParamaters_;
        } else {
          result.linkedParamaters_ = linkedParamatersBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        if (endOfFrameBuilder_ == null) {
          result.endOfFrame_ = endOfFrame_;
        } else {
          result.endOfFrame_ = endOfFrameBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataFieldsProto.DataFields) {
          return mergeFrom((DataFieldsProto.DataFields)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataFieldsProto.DataFields other) {
        if (other == DataFieldsProto.DataFields.getDefaultInstance()) return this;
        if (other.hasSubType()) {
          setSubType(other.getSubType());
        }
        if (instrumentBuilder_ == null) {
          if (!other.instrument_.isEmpty()) {
            if (instrument_.isEmpty()) {
              instrument_ = other.instrument_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInstrumentIsMutable();
              instrument_.addAll(other.instrument_);
            }
            onChanged();
          }
        } else {
          if (!other.instrument_.isEmpty()) {
            if (instrumentBuilder_.isEmpty()) {
              instrumentBuilder_.dispose();
              instrumentBuilder_ = null;
              instrument_ = other.instrument_;
              bitField0_ = (bitField0_ & ~0x00000002);
              instrumentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInstrumentFieldBuilder() : null;
            } else {
              instrumentBuilder_.addAllMessages(other.instrument_);
            }
          }
        }
        if (linkedParamatersBuilder_ == null) {
          if (!other.linkedParamaters_.isEmpty()) {
            if (linkedParamaters_.isEmpty()) {
              linkedParamaters_ = other.linkedParamaters_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureLinkedParamatersIsMutable();
              linkedParamaters_.addAll(other.linkedParamaters_);
            }
            onChanged();
          }
        } else {
          if (!other.linkedParamaters_.isEmpty()) {
            if (linkedParamatersBuilder_.isEmpty()) {
              linkedParamatersBuilder_.dispose();
              linkedParamatersBuilder_ = null;
              linkedParamaters_ = other.linkedParamaters_;
              bitField0_ = (bitField0_ & ~0x00000004);
              linkedParamatersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLinkedParamatersFieldBuilder() : null;
            } else {
              linkedParamatersBuilder_.addAllMessages(other.linkedParamaters_);
            }
          }
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasEndOfFrame()) {
          mergeEndOfFrame(other.getEndOfFrame());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSubType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DataFieldsProto.DataFields parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DataFieldsProto.DataFields) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int subType_ = 1;
      /**
       * <code>required .DataFields.SubType subType = 1;</code>
       */
      public boolean hasSubType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .DataFields.SubType subType = 1;</code>
       */
      public DataFieldsProto.DataFields.SubType getSubType() {
        DataFieldsProto.DataFields.SubType result = DataFieldsProto.DataFields.SubType.valueOf(subType_);
        return result == null ? DataFieldsProto.DataFields.SubType.DEFAULT : result;
      }
      /**
       * <code>required .DataFields.SubType subType = 1;</code>
       */
      public Builder setSubType(DataFieldsProto.DataFields.SubType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        subType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .DataFields.SubType subType = 1;</code>
       */
      public Builder clearSubType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        subType_ = 1;
        onChanged();
        return this;
      }

      private java.util.List<CommonProto.Instrument> instrument_ =
        java.util.Collections.emptyList();
      private void ensureInstrumentIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          instrument_ = new java.util.ArrayList<CommonProto.Instrument>(instrument_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CommonProto.Instrument, CommonProto.Instrument.Builder, CommonProto.InstrumentOrBuilder> instrumentBuilder_;

      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public java.util.List<CommonProto.Instrument> getInstrumentList() {
        if (instrumentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(instrument_);
        } else {
          return instrumentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public int getInstrumentCount() {
        if (instrumentBuilder_ == null) {
          return instrument_.size();
        } else {
          return instrumentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public CommonProto.Instrument getInstrument(int index) {
        if (instrumentBuilder_ == null) {
          return instrument_.get(index);
        } else {
          return instrumentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public Builder setInstrument(
          int index, CommonProto.Instrument value) {
        if (instrumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentIsMutable();
          instrument_.set(index, value);
          onChanged();
        } else {
          instrumentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public Builder setInstrument(
          int index, CommonProto.Instrument.Builder builderForValue) {
        if (instrumentBuilder_ == null) {
          ensureInstrumentIsMutable();
          instrument_.set(index, builderForValue.build());
          onChanged();
        } else {
          instrumentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public Builder addInstrument(CommonProto.Instrument value) {
        if (instrumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentIsMutable();
          instrument_.add(value);
          onChanged();
        } else {
          instrumentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public Builder addInstrument(
          int index, CommonProto.Instrument value) {
        if (instrumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentIsMutable();
          instrument_.add(index, value);
          onChanged();
        } else {
          instrumentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public Builder addInstrument(
          CommonProto.Instrument.Builder builderForValue) {
        if (instrumentBuilder_ == null) {
          ensureInstrumentIsMutable();
          instrument_.add(builderForValue.build());
          onChanged();
        } else {
          instrumentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public Builder addInstrument(
          int index, CommonProto.Instrument.Builder builderForValue) {
        if (instrumentBuilder_ == null) {
          ensureInstrumentIsMutable();
          instrument_.add(index, builderForValue.build());
          onChanged();
        } else {
          instrumentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public Builder addAllInstrument(
          java.lang.Iterable<? extends CommonProto.Instrument> values) {
        if (instrumentBuilder_ == null) {
          ensureInstrumentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, instrument_);
          onChanged();
        } else {
          instrumentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public Builder clearInstrument() {
        if (instrumentBuilder_ == null) {
          instrument_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          instrumentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public Builder removeInstrument(int index) {
        if (instrumentBuilder_ == null) {
          ensureInstrumentIsMutable();
          instrument_.remove(index);
          onChanged();
        } else {
          instrumentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public CommonProto.Instrument.Builder getInstrumentBuilder(
          int index) {
        return getInstrumentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public CommonProto.InstrumentOrBuilder getInstrumentOrBuilder(
          int index) {
        if (instrumentBuilder_ == null) {
          return instrument_.get(index);  } else {
          return instrumentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public java.util.List<? extends CommonProto.InstrumentOrBuilder>
           getInstrumentOrBuilderList() {
        if (instrumentBuilder_ != null) {
          return instrumentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(instrument_);
        }
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public CommonProto.Instrument.Builder addInstrumentBuilder() {
        return getInstrumentFieldBuilder().addBuilder(
            CommonProto.Instrument.getDefaultInstance());
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public CommonProto.Instrument.Builder addInstrumentBuilder(
          int index) {
        return getInstrumentFieldBuilder().addBuilder(
            index, CommonProto.Instrument.getDefaultInstance());
      }
      /**
       * <code>repeated .Instrument instrument = 2;</code>
       */
      public java.util.List<CommonProto.Instrument.Builder>
           getInstrumentBuilderList() {
        return getInstrumentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CommonProto.Instrument, CommonProto.Instrument.Builder, CommonProto.InstrumentOrBuilder>
          getInstrumentFieldBuilder() {
        if (instrumentBuilder_ == null) {
          instrumentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CommonProto.Instrument, CommonProto.Instrument.Builder, CommonProto.InstrumentOrBuilder>(
                  instrument_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          instrument_ = null;
        }
        return instrumentBuilder_;
      }

      private java.util.List<CommonProto.LinkedParameter> linkedParamaters_ =
        java.util.Collections.emptyList();
      private void ensureLinkedParamatersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          linkedParamaters_ = new java.util.ArrayList<CommonProto.LinkedParameter>(linkedParamaters_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CommonProto.LinkedParameter, CommonProto.LinkedParameter.Builder, CommonProto.LinkedParameterOrBuilder> linkedParamatersBuilder_;

      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public java.util.List<CommonProto.LinkedParameter> getLinkedParamatersList() {
        if (linkedParamatersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(linkedParamaters_);
        } else {
          return linkedParamatersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public int getLinkedParamatersCount() {
        if (linkedParamatersBuilder_ == null) {
          return linkedParamaters_.size();
        } else {
          return linkedParamatersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public CommonProto.LinkedParameter getLinkedParamaters(int index) {
        if (linkedParamatersBuilder_ == null) {
          return linkedParamaters_.get(index);
        } else {
          return linkedParamatersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder setLinkedParamaters(
          int index, CommonProto.LinkedParameter value) {
        if (linkedParamatersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.set(index, value);
          onChanged();
        } else {
          linkedParamatersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder setLinkedParamaters(
          int index, CommonProto.LinkedParameter.Builder builderForValue) {
        if (linkedParamatersBuilder_ == null) {
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.set(index, builderForValue.build());
          onChanged();
        } else {
          linkedParamatersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder addLinkedParamaters(CommonProto.LinkedParameter value) {
        if (linkedParamatersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.add(value);
          onChanged();
        } else {
          linkedParamatersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder addLinkedParamaters(
          int index, CommonProto.LinkedParameter value) {
        if (linkedParamatersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.add(index, value);
          onChanged();
        } else {
          linkedParamatersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder addLinkedParamaters(
          CommonProto.LinkedParameter.Builder builderForValue) {
        if (linkedParamatersBuilder_ == null) {
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.add(builderForValue.build());
          onChanged();
        } else {
          linkedParamatersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder addLinkedParamaters(
          int index, CommonProto.LinkedParameter.Builder builderForValue) {
        if (linkedParamatersBuilder_ == null) {
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.add(index, builderForValue.build());
          onChanged();
        } else {
          linkedParamatersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder addAllLinkedParamaters(
          java.lang.Iterable<? extends CommonProto.LinkedParameter> values) {
        if (linkedParamatersBuilder_ == null) {
          ensureLinkedParamatersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, linkedParamaters_);
          onChanged();
        } else {
          linkedParamatersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder clearLinkedParamaters() {
        if (linkedParamatersBuilder_ == null) {
          linkedParamaters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          linkedParamatersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public Builder removeLinkedParamaters(int index) {
        if (linkedParamatersBuilder_ == null) {
          ensureLinkedParamatersIsMutable();
          linkedParamaters_.remove(index);
          onChanged();
        } else {
          linkedParamatersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public CommonProto.LinkedParameter.Builder getLinkedParamatersBuilder(
          int index) {
        return getLinkedParamatersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public CommonProto.LinkedParameterOrBuilder getLinkedParamatersOrBuilder(
          int index) {
        if (linkedParamatersBuilder_ == null) {
          return linkedParamaters_.get(index);  } else {
          return linkedParamatersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public java.util.List<? extends CommonProto.LinkedParameterOrBuilder>
           getLinkedParamatersOrBuilderList() {
        if (linkedParamatersBuilder_ != null) {
          return linkedParamatersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(linkedParamaters_);
        }
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public CommonProto.LinkedParameter.Builder addLinkedParamatersBuilder() {
        return getLinkedParamatersFieldBuilder().addBuilder(
            CommonProto.LinkedParameter.getDefaultInstance());
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public CommonProto.LinkedParameter.Builder addLinkedParamatersBuilder(
          int index) {
        return getLinkedParamatersFieldBuilder().addBuilder(
            index, CommonProto.LinkedParameter.getDefaultInstance());
      }
      /**
       * <code>repeated .LinkedParameter linkedParamaters = 3;</code>
       */
      public java.util.List<CommonProto.LinkedParameter.Builder>
           getLinkedParamatersBuilderList() {
        return getLinkedParamatersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CommonProto.LinkedParameter, CommonProto.LinkedParameter.Builder, CommonProto.LinkedParameterOrBuilder>
          getLinkedParamatersFieldBuilder() {
        if (linkedParamatersBuilder_ == null) {
          linkedParamatersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CommonProto.LinkedParameter, CommonProto.LinkedParameter.Builder, CommonProto.LinkedParameterOrBuilder>(
                  linkedParamaters_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          linkedParamaters_ = null;
        }
        return linkedParamatersBuilder_;
      }

      private long startTime_ ;
      /**
       * <code>optional int64 startTime = 5;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 startTime = 5;</code>
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>optional int64 startTime = 5;</code>
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000008;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 startTime = 5;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>optional int64 endTime = 6;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 endTime = 6;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>optional int64 endTime = 6;</code>
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000010;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 endTime = 6;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private CommonProto.EndOfFrame endOfFrame_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonProto.EndOfFrame, CommonProto.EndOfFrame.Builder, CommonProto.EndOfFrameOrBuilder> endOfFrameBuilder_;
      /**
       * <code>optional .EndOfFrame endOfFrame = 7;</code>
       */
      public boolean hasEndOfFrame() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .EndOfFrame endOfFrame = 7;</code>
       */
      public CommonProto.EndOfFrame getEndOfFrame() {
        if (endOfFrameBuilder_ == null) {
          return endOfFrame_ == null ? CommonProto.EndOfFrame.getDefaultInstance() : endOfFrame_;
        } else {
          return endOfFrameBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .EndOfFrame endOfFrame = 7;</code>
       */
      public Builder setEndOfFrame(CommonProto.EndOfFrame value) {
        if (endOfFrameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          endOfFrame_ = value;
          onChanged();
        } else {
          endOfFrameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .EndOfFrame endOfFrame = 7;</code>
       */
      public Builder setEndOfFrame(
          CommonProto.EndOfFrame.Builder builderForValue) {
        if (endOfFrameBuilder_ == null) {
          endOfFrame_ = builderForValue.build();
          onChanged();
        } else {
          endOfFrameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .EndOfFrame endOfFrame = 7;</code>
       */
      public Builder mergeEndOfFrame(CommonProto.EndOfFrame value) {
        if (endOfFrameBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              endOfFrame_ != null &&
              endOfFrame_ != CommonProto.EndOfFrame.getDefaultInstance()) {
            endOfFrame_ =
              CommonProto.EndOfFrame.newBuilder(endOfFrame_).mergeFrom(value).buildPartial();
          } else {
            endOfFrame_ = value;
          }
          onChanged();
        } else {
          endOfFrameBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .EndOfFrame endOfFrame = 7;</code>
       */
      public Builder clearEndOfFrame() {
        if (endOfFrameBuilder_ == null) {
          endOfFrame_ = null;
          onChanged();
        } else {
          endOfFrameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .EndOfFrame endOfFrame = 7;</code>
       */
      public CommonProto.EndOfFrame.Builder getEndOfFrameBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getEndOfFrameFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .EndOfFrame endOfFrame = 7;</code>
       */
      public CommonProto.EndOfFrameOrBuilder getEndOfFrameOrBuilder() {
        if (endOfFrameBuilder_ != null) {
          return endOfFrameBuilder_.getMessageOrBuilder();
        } else {
          return endOfFrame_ == null ?
              CommonProto.EndOfFrame.getDefaultInstance() : endOfFrame_;
        }
      }
      /**
       * <code>optional .EndOfFrame endOfFrame = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonProto.EndOfFrame, CommonProto.EndOfFrame.Builder, CommonProto.EndOfFrameOrBuilder>
          getEndOfFrameFieldBuilder() {
        if (endOfFrameBuilder_ == null) {
          endOfFrameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CommonProto.EndOfFrame, CommonProto.EndOfFrame.Builder, CommonProto.EndOfFrameOrBuilder>(
                  getEndOfFrame(),
                  getParentForChildren(),
                  isClean());
          endOfFrame_ = null;
        }
        return endOfFrameBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataFields)
    }

    // @@protoc_insertion_point(class_scope:DataFields)
    private static final DataFieldsProto.DataFields DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataFieldsProto.DataFields();
    }

    public static DataFieldsProto.DataFields getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DataFields>
        PARSER = new com.google.protobuf.AbstractParser<DataFields>() {
      public DataFields parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataFields(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataFields> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataFields> getParserForType() {
      return PARSER;
    }

    public DataFieldsProto.DataFields getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataFields_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataFields_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025DataFieldsProto.proto\032\021CommonProto.pro" +
      "to\"\356\002\n\nDataFields\022$\n\007subType\030\001 \002(\0162\023.Dat" +
      "aFields.SubType\022\037\n\ninstrument\030\002 \003(\0132\013.In" +
      "strument\022*\n\020linkedParamaters\030\003 \003(\0132\020.Lin" +
      "kedParameter\022\021\n\tstartTime\030\005 \001(\003\022\017\n\007endTi" +
      "me\030\006 \001(\003\022\037\n\nendOfFrame\030\007 \001(\0132\013.EndOfFram" +
      "e\"\247\001\n\007SubType\022\013\n\007DEFAULT\020\001\022\n\n\006UPDATE\020\002\022\017" +
      "\n\013UNSUBSCRIBE\020\003\022\014\n\010SNAPSHOT\020\004\022\024\n\020DEFAULT" +
      "_GROUPING\020\005\022\023\n\017UPDATE_GROUPING\020\006\022\017\n\013GET_" +
      "HISTORY\020\007\022\030\n\024UNSUBSCRIBE_GROUPING\020\010\022\016\n\nR" +
      "EF_UPDATE\020\tB.\n,com.spcapitaliq.realtime." +
      "common.proto.domain"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CommonProto.getDescriptor(),
        }, assigner);
    internal_static_DataFields_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataFields_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataFields_descriptor,
        new java.lang.String[] { "SubType", "Instrument", "LinkedParamaters", "StartTime", "EndTime", "EndOfFrame", });
    CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
